# Generated by Django 4.2.4 on 2023-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('user_login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('user_password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
            ],
            options={
                'verbose_name': 'Телеграм Пользователь',
                'verbose_name_plural': 'Телеграм Пользователи',
                'db_table': 'telegram_users',
                'ordering': ['-registered_at'],
            },
        ),
    ]
