# Generated by Django 4.2.4 on 2023-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_comment_options_alter_product_table_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FilePathField(blank=True),
        ),
    ]
