# Generated by Django 4.2.4 on 2023-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID сообщения'),
            preserve_default=False,
        ),
    ]
